### ISSUE TITLE
Define "de-identification"

### ISSUE THREAD

**Issue by simsong** [chop-dbhi/dicom-pipeline#9]
Hi. It would be useful to know if this system's de-identification capabilities are limited to stripping PII out of the DICOM headers, or if it also attempts to de-identify the multimedia content. It appears to me that it only does the former. Please clarify.

**Comment by jeffmax** [comment]
It does not attempt to de-identify the multi-media, but it does provide an
application to aid in human review:
https://github.com/chop-dbhi/django-dicom-review

**Comment by simsong** [comment]
Okay. Thanks.
